### ISSUE TITLE
nfT field becomes very big in scalarAdvection for velocities not zero

### ISSUE THREAD

**Issue by happyKitesurfer** [exasim-project/FoamAdapter#33]
![Bildschirmfoto vom 2024-11-26 21-59-32](https://github.com/user-attachments/assets/a845a313-957c-4efc-b235-a2669b2a2294)

I initialized the velocity in the scalarAdvection tutorial like this:

```
/*--------------------------------*- C++ -*----------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  v2306                                 |
|   \\  /    A nd           | Website:  www.openfoam.com                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       volVectorField;
    object      U;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

dimensions      [0 1 -1 0 0 0 0];

internalField   uniform (0 -1  0);

boundaryField
{
    fixedWalls
    {
        type            zeroGradient;
    }

}


// ************************************************************************* //

```
After a few time step the nfF field became very big. See the figure above. Did you have similar issues?

**Comment by happyKitesurfer** [comment]
It happen on both

**Comment by happyKitesurfer** [comment]
Are you working on the implementation of the div Schemes on a particular branch?

**Comment by greole** [comment]
This is more of a shot in the dark. We merged this PR https://github.com/exasim-project/NeoFOAM/pull/102 which modifies the schemes. So you could try to update your NeoFOAM folder and rebuild and run everything.

**Comment by happyKitesurfer** [comment]
I wrote out the nfphi field for the 100x100 case using                 write(nfPhi.internalField(), mesh, "nfPhi");

FoamFile
{
    version     2.0;
    format      ascii;
    arch        "LSB;label=32;scalar=64";
    class       volScalarField;
    location    "0.1";
    object      nfPhi;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

dimensions      [0 0 0 0 0 0 0];

internalField   nonuniform List<scalar>
10000

 and also the phi field from OpenFoam

FoamFile
{
    version     2.0;
    format      ascii;
    arch        "LSB;label=32;scalar=64";
    class       surfaceScalarField;
    location    "0.1";
    object      phi;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

dimensions      [0 3 -1 0 0 0 0];

oriented        oriented;

internalField   nonuniform List<scalar>
19800

In an 100x100 there should be 99*100 + 100*99 = 19800 internal phases. It there a reason the nfPhi has only 10000 internal faces?

**Comment by HenningScheufler** [comment]
Please have a look at PR #35. It is the most uptodate branch and is able to compute the scalarAdvection on CPU and CPU

**Comment by happyKitesurfer** [comment]
When I try to use the clang compiler: cmake -D CMAKE_CXX_COMPILER=clang-18 -D MPI_CXX_COMPILER=clang-18  --preset develop, I got the error:
-- Set CPM_USE_LOCAL_PACKAGES=ON by default.
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) (Required is at least version "3.1")
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPI (missing: MPI_CXX_FOUND) (found suitable version "3.1",
  minimum required is "3.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindMPI.cmake:1830 (find_package_handle_standard_args)
  NeoFOAM/cmake/CxxThirdParty.cmake:9 (find_package)
  NeoFOAM/CMakeLists.txt:64 (include)

When I try to use gcc the compilation does not work. How did you manage to use clang? I'm having ubuntu 22.04 LTS

**Comment by greole** [comment]
Does  `CC=clang CXX=clang++ cmake --preset develop` work?

**Comment by happyKitesurfer** [comment]
I have another question:

public:

    /**
     * @brief Constructor for GeometricFieldMixin.
     *
     * @param exec The executor object.
     * @param mesh The unstructured mesh object.
     * @param field The domain field object.
     */
    GeometricFieldMixin(
        const Executor& exec,
        std::string fieldName,
        const UnstructuredMesh& mesh,
        const DomainField<ValueType>& field
    )
        : exec_(exec), name(fieldName), mesh_(mesh), field_(field)

however 

protected:

    Executor exec_;                // The executor object
    std::string name_;             // The name of the field
    const UnstructuredMesh& mesh_; // The unstructured mesh object
    DomainField<ValueType> field_; // The domain field object

};

should the constructor call not be:

        : exec_(exec), name_(fieldName), mesh_(mesh), field_(field)

**Comment by greole** [comment]
Maybe i am staring at code for too long today, but i don't see the issue?

**Comment by greole** [comment]
ahh i see the missing underscore.

**Comment by greole** [comment]
But i think that is an outdated version of NeoFOAM. See the current version of [geometricField.hpp](
https://github.com/exasim-project/NeoFOAM/blob/main/include/NeoFOAM/finiteVolume/cellCentred/fields/geometricField.hpp) on our main branch.

**Comment by happyKitesurfer** [comment]
CC=clang CXX=clang++ cmake --preset develop
Preset CMake variables:

  CMAKE_BUILD_TYPE="Debug"
  FOAMADAPTER_BUILD_BENCHMARKS="ON"
  FOAMADAPTER_BUILD_TESTS="ON"
  Kokkos_ENABLE_DEBUG="ON"
  Kokkos_ENABLE_DEBUG_BOUNDS_CHECK="ON"
  Kokkos_ENABLE_SERIAL="ON"
  NEOFOAM_DEVEL_TOOLS="ON"

CMake Error at /usr/share/cmake-3.22/Modules/CMakeDetermineCCompiler.cmake:49 (message):
  Could not find compiler set in environment variable CC:

  clang.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

**Comment by happyKitesurfer** [comment]
CC=clang-18 CXX=clang++-18 cmake --preset develop
Preset CMake variables:

  CMAKE_BUILD_TYPE="Debug"
  FOAMADAPTER_BUILD_BENCHMARKS="ON"
  FOAMADAPTER_BUILD_TESTS="ON"
  Kokkos_ENABLE_DEBUG="ON"
  Kokkos_ENABLE_DEBUG_BOUNDS_CHECK="ON"
  Kokkos_ENABLE_SERIAL="ON"
  NEOFOAM_DEVEL_TOOLS="ON"

-- The C compiler identification is Clang 18.1.8
-- The CXX compiler identification is Clang 18.1.8
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang-18 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/bin/clang++-18
-- Check for working CXX compiler: /usr/bin/clang++-18 - broken
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/usr/bin/clang++-18"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/michael/NeoFOAM/FoamAdapter/build/develop/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/ninja cmTC_708aa && [1/2] Building CXX object CMakeFiles/cmTC_708aa.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_708aa
    FAILED: cmTC_708aa 
    : && /usr/bin/clang++-18   CMakeFiles/cmTC_708aa.dir/testCXXCompiler.cxx.o -o cmTC_708aa   && :
    /usr/bin/ld: -lstdc++ kann nicht gefunden werden: Datei oder Verzeichnis nicht gefunden
    clang++-18: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)

**Comment by greole** [comment]
`/usr/bin/ld: -lstdc++` -> try to install `libc++`. On ubuntu probably `apt install libc++`

**Comment by happyKitesurfer** [comment]
I got rid of the above error by executing: 

CC=clang-18 CXX=clang++-18  cmake --preset develop -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu

however the next error popped up :) : 

CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPI (missing: MPI_CXX_FOUND) (found suitable version "3.1",
  minimum required is "3.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindMPI.cmake:1830 (find_package_handle_standard_args)
  NeoFOAM/cmake/CxxThirdParty.cmake:9 (find_package)
  NeoFOAM/CMakeLists.txt:64 (include)

**Comment by happyKitesurfer** [comment]
The problem when using clang as compiler it does not find mpi

when using the default setting


cmake   --preset develop

Mpi is found

-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found suitable version "3.1", minimum required is "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found suitable version "3.1", minimum required is "3.1")

**Comment by happyKitesurfer** [comment]
ok this one worked:

cmake -D CMAKE_C_COMPILER=clang-18  --preset develop

This one not

cmake -D CMAKE_CXX_COMPILER=clang-18  --preset develop

**Comment by happyKitesurfer** [comment]
with this the preset worked

sudo apt install libstdc++-12-dev

cmake -D CMAKE_C_COMPILER=clang-18 -D CMAKE_CXX_COMPILER=clang++-18   --preset develop -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/

**Comment by happyKitesurfer** [comment]
Another remark: The compilation with  cuda 12.3 works but with 12.6 since 12.3 is the newest cuda version compatible with clang18

**Comment by happyKitesurfer** [comment]
The only thing is that I get the error /usr/bin/ld: lib/libNeoFOAM.so: undefined reference to `cudaGetDeviceProperties_v2'

when trying to compile with clang18 and cuda12.3 and also cuda12.6. 

Just a brief summary what I'm trying to do: I'm trying to get the scalarAdvection with dsl compiled. I'm using on the NeoFoam side the branch: https://github.com/exasim-project/NeoFOAM/tree/feat/fieldDataBase and on the foamAdapter side this branch: dsl/operatorIntergration https://github.com/exasim-project/FoamAdapter/tree/dsl/operatorIntergration. 

I'm I doing something wrong? Which branches should I use to the the scalarAdvection with DSL running?

**Comment by HenningScheufler** [comment]
We are currently finishing PR the feat/database and after it is merged the PR  Feat/operator from inputs #182  would need to be updated.
After this the implementation of the DSL should be fairly straightforward

**Comment by happyKitesurfer** [comment]
@HenningScheufler  I tried to compile https://github.com/exasim-project/FoamAdapter/tree/feat/operatorFromInputs and included also the submodule present in the branch. However i got the error 

/home/michael/NeoFOAM/FoamAdapter/benchmarks/scalarAdvection/scalarAdvection.cpp(148): error: name followed by "::" must be a class or namespace name
                      fvcc::impOp::ddt(neoT)
                            ^

1 error detected in the compilation of "/home/michael/NeoFOAM/FoamAdapter/benchmarks/scalarAdvection/scalarAdvection.cpp".


I could not find were the namespace impOp is defined. I could only find:

namespace NeoFOAM::finiteVolume::cellCentred::expOp

**Comment by HenningScheufler** [comment]
This file should not be present in the branch are you sure the branch is uptodate

https://github.com/exasim-project/FoamAdapter/tree/feat/operatorFromInputs

**Comment by greole** [comment]
Also i am currently updating the branches. Might take some minutes to work again.

**Comment by greole** [comment]
@happyKitesurfer can you perform a clean build and try again. (eg. delete the build folder, and `git pull origin feat/operatorFromInputs`)

**Comment by happyKitesurfer** [comment]
great with the latest commit the scalarAdvection is working. The compilation is successful with clang but not with gcc.

**Comment by greole** [comment]
Ok great, good to hear! I'll close this issue for now since getting foamAdapter to compile seems to be a different issue.
