### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by HenningScheufler** [exasim-project/FoamAdapter#2]
With the following build configuration FoamAdapter does not compile:

```bash
#!/bin/bash

# Run CMake to generate the build files
# -DCMAKE_INSTALL_PREFIX=$PWD/FoamAdapter \
cmake  -S . -B build  -DCMAKE_BUILD_TYPE=Release \
        -DNEOFOAM_BUILD_TESTS=ON \
        -DKokkos_ENABLE_SERIAL=ON \
        -DKokkos_ENABLE_OPENMP=ON
        # -DKokkos_ENABLE_CUDA=ON \
        # -DKokkos_ENABLE_CUDA_CONSTEXPR=ON
        # -DKokkos_ARCH_NATIVE=ON \
        # -DKokkos_ENABLE_AGGRESSIVE_VECTORIZATION=ON

# Build the project using make
cmake --build build -j
# cmake --install build
```

With the following error
```

/home/henning/OpenFOAM/OpenFOAM-v2306/src/OpenFOAM/lnInclude/DiagonalMatrix.H:85:30: error: expected unqualified-id before ‘const’
   85 |         DiagonalMatrix<Type>(const label n, const Foam::zero);
      |                              ^~~~~
/home/henning/OpenFOAM/OpenFOAM-v2306/src/OpenFOAM/lnInclude/DiagonalMatrix.H:85:30: error: expected ‘)’ before ‘const’
   85 |         DiagonalMatrix<Type>(const label n, const Foam::zero);
      |                             ~^~~~~
      |                              )
/home/henning/OpenFOAM/OpenFOAM-v2306/src/OpenFOAM/lnInclude/DiagonalMatrix.H:88:30: error: expected unqualified-id before ‘const’
   88 |         DiagonalMatrix<Type>(const label n, const Type& val);
      |                              ^~~~~
/home/henning/OpenFOAM/OpenFOAM-v2306/src/OpenFOAM/lnInclude/DiagonalMatrix.H:88:30: error: expected ‘)’ before ‘const’
   88 |         DiagonalMatrix<Type>(const label n, const Type& val);
      |                             ~^~~~~
      |                              )
/home/henning/OpenFOAM/OpenFOAM-v2306/src/OpenFOAM/lnInclude/DiagonalMatrix.H:92:30: error: expected unqualified-id before ‘const’
   92 |         DiagonalMatrix<Type>(const Matrix<Form, Type>& mat);
      |                              ^~~~~
/home/henning/OpenFOAM/OpenFOAM-v2306/src/OpenFOAM/lnInclude/DiagonalMatrix.H:92:30: error: expected ‘)’ before ‘const’
   92 |         DiagonalMatrix<Type>(const Matrix<Form, Type>& mat);
```

**Comment by HenningScheufler** [comment]
@greole @MarcelKoch @bevanwsjones

**Comment by HenningScheufler** [comment]
OpenFOAM does not compile with gcc and the cpp std 20. (tested on Ubuntu 22.04)

The compiler version to compile NeoFOAM are quite high:
```
clang > 17.00
gcc incompatible (for non GPU compilation)
```
We could consider downgrading neofoam to cppstd 17. This would require only the implementation of std::span

**Comment by greole** [comment]
> OpenFOAM does not compile with gcc and the cpp std 20. (tested on Ubuntu 22.04)

Correct me if I'm wrong but the choice for cpp 20 for NeoFOAM doens't affect the compilation of Openfoam, which should can be compiled independently with cpp 14.

> The compiler version to compile NeoFOAM are quite high:

Yes that is true, but that is only the case now. Ubuntu just had a new LTS release 24.04 which ships clang 18 and gcc 10. So soon this shouldn't be an issue.

**Comment by greole** [comment]
See https://github.com/exasim-project/FoamAdapter/blob/main/src/benchmarks/explicitOperators/CMakeLists.txt

**Comment by FoamScience** [comment]
Just wanted to mention that this is related to:
- [P1021R6: Filling holes in Class Template Argument Deduction](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p1021r6.html)
- and probably indirectly to [P0634R3: Down with typename!](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0634r3.html)

Clang is known for permissible syntactic constraints; but I'd prefer Gcc's way of doing things for this one.
Here is a small playground to poke around this issue if you like to: https://godbolt.org/z/rcMG39Gaj

**Solution**:
1. Either; we raise this with OpenFOAM devs
2. Or just sed `DiagonalMatrix.H` header to remove `<Type>` from `DiagonalMatrix<Type>` (right now this works)

we see this error because FoamAdapter includes some header that includes `DiagonalMatrix.H` (probably `dimensionSets.H`)

**Comment by HenningScheufler** [comment]
I would prefer the solution to contact the devs to fix this issue.  The other solution is not maintainable.

**Comment by HenningScheufler** [comment]
I opened a issue on develop github:

https://develop.openfoam.com/Development/openfoam/-/issues/3168

**Comment by greole** [comment]
The issue is that it is a problem with C++20 which OpenFOAM doesn't support at the moment. But yes maybe they'll fix it.

**Comment by HenningScheufler** [comment]
I created a fix for this issue it only requires minor changes to 8 files

**Comment by FoamScience** [comment]
@HenningScheufler's patch should take care of this.
But here is a fun way to solve these minor issues for future reference;
that's how I did it originally to my OpenFOAM installation, there was no patch because installed from package repos 😄 
Enjoy: [FoamScience/openfoam-code-transformations](https://github.com/FoamScience/openfoam-code-transformations)

**Comment by HenningScheufler** [comment]
This is resolved with of2406
